### ISSUE TITLE
Requesting making Window.samples public

### ISSUE THREAD

**Issue by antimora** [klangner/dsp.rs#64]
I have a use case where I want to access the window samples and do the multiplication myself. Currently, the `samples` in `Window` struct is private.

**Comment by klangner** [comment]
You can get it as slice:
https://github.com/klangner/dsp.rs/blob/3f28224b666d1d6a2a4418795e05ed3a27287549/src/window.rs#L24

**Comment by antimora** [comment]
@klangner, thanks it should work then but I am not seeing in the [latest published version `dsp = "0.10.1"`](https://docs.rs/dsp/0.10.1/dsp/window/struct.Window.html). Have the changes been published to crates.io repo? Sorry if I am not seeing something.

**Comment by klangner** [comment]
Yes, you are right. It was only in master not in published version.
I have just published a new version `0.10.2` with all changes, so the function `as_slice` is visible now.

**Comment by klangner** [comment]
I will close it since I think it is resolved.
Feel free to reopen if there is still problem
